/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iloan.pawn;

import iloan.customer.Customer;
import iloan.kernel.Utilities;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author mrogers
 */
public class FrmNewPawn extends javax.swing.JInternalFrame
{

    /**
     * Creates new form FrmNewPawn
     */
    public FrmNewPawn()
    {
        initComponents();
        populateLists();
    }
    
    private void loadCustomerInfo()
    {
        int custID = Integer.valueOf(tblCustomers.getValueAt(tblCustomers.getSelectedRow(), 0).toString());
        String fullName = Customer.getFullNameByID(custID);
        txtCustID.setText(String.valueOf(custID));
        txtCustName.setText(fullName);
        pawnTabbedPane.setSelectedIndex(pawnTabbedPane.getSelectedIndex() + 1);
    }
    
    private void populateLists()
    {
        //Load the customers
        tblCustomers.setModel(Customer.getCustomerTable());

        //Set default dates
        Calendar today = new GregorianCalendar();
        today.setTime(new Date());
        
        Calendar nextMonth = new GregorianCalendar();
        nextMonth.setTime(new Date());
        nextMonth.add(Calendar.MONTH, 1);
        nextMonth.add(Calendar.DATE, -1);
        calRecievedDate.setDate(today.getTime());
        calDueDate.setDate(nextMonth.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pawnTabbedPane = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        jYTableScrollPane1 = new de.javasoft.swing.JYTableScrollPane();
        tblCustomers = new de.javasoft.swing.JYTable();
        cmdCancel5 = new javax.swing.JButton();
        cmdNext5 = new javax.swing.JButton();
        generalPanel = new javax.swing.JPanel();
        lblNoOfItems = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        lblCustName = new javax.swing.JLabel();
        lblPawnAmount = new javax.swing.JLabel();
        txtNoOfItems = new javax.swing.JTextField();
        lblRecievedDate = new javax.swing.JLabel();
        cmdCancel = new javax.swing.JButton();
        cmdNext = new javax.swing.JButton();
        lblDueDate = new javax.swing.JLabel();
        lblInterestRate = new javax.swing.JLabel();
        lblInterestDue = new javax.swing.JLabel();
        txtInterestDue = new javax.swing.JTextField();
        cmdResetForm = new javax.swing.JButton();
        lblCustID = new javax.swing.JLabel();
        lblTotalDue = new javax.swing.JLabel();
        txtTotalValue = new javax.swing.JTextField();
        txtPawnAmount = new javax.swing.JTextField();
        txtInterestRate = new javax.swing.JTextField();
        txtTotalDue = new javax.swing.JTextField();
        calRecievedDate = new com.toedter.calendar.JDateChooser();
        calDueDate = new com.toedter.calendar.JDateChooser();
        itemsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        cmdCancel1 = new javax.swing.JButton();
        cmdSave = new javax.swing.JButton();
        cmdRemove = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("New Pawn");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/ruby_add.png"))); // NOI18N

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "DOB", "Rating"
            }
        ));
        tblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomersMouseClicked(evt);
            }
        });
        jYTableScrollPane1.setViewportView(tblCustomers);

        cmdCancel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/cross.png"))); // NOI18N
        cmdCancel5.setText("Cancel");
        cmdCancel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel5ActionPerformed(evt);
            }
        });

        cmdNext5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/resultset_next.png"))); // NOI18N
        cmdNext5.setText("Next");
        cmdNext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNext5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jYTableScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdNext5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdCancel5)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jYTableScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel5)
                    .addComponent(cmdNext5))
                .addContainerGap())
        );

        pawnTabbedPane.addTab(" Search", new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/find.png")), searchPanel); // NOI18N

        lblNoOfItems.setText("No. of Items:");

        lblTotalValue.setText("Total Value:");

        txtCustID.setEditable(false);
        txtCustID.setToolTipText("The customer's unique ID in the system.");

        txtCustName.setEditable(false);
        txtCustName.setToolTipText("The Customer's name for reference.");

        lblCustName.setText("Customer:");

        lblPawnAmount.setText("Pawn Amount:");

        txtNoOfItems.setEditable(false);
        txtNoOfItems.setToolTipText("The number of items currently on the pawn ticket.");

        lblRecievedDate.setText("Recieved Date:");

        cmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/cross.png"))); // NOI18N
        cmdCancel.setMnemonic('C');
        cmdCancel.setText("Cancel");
        cmdCancel.setToolTipText("Closes this window without saving any changes.");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelcancel(evt);
            }
        });

        cmdNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/resultset_next.png"))); // NOI18N
        cmdNext.setMnemonic('N');
        cmdNext.setText("Next");
        cmdNext.setToolTipText("Moves to the next tab where you can continue to enter information.");
        cmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextnext(evt);
            }
        });

        lblDueDate.setText("Due Date:");

        lblInterestRate.setText("Interest Rate:");

        lblInterestDue.setText("Interest Due:");

        txtInterestDue.setEditable(false);
        txtInterestDue.setToolTipText("The total interest due based in the rate and pawn amount.");

        cmdResetForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/arrow_refresh.png"))); // NOI18N
        cmdResetForm.setText("Reset Form");
        cmdResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetFormActionPerformed(evt);
            }
        });

        lblCustID.setText("Cust. ID:");

        lblTotalDue.setText("Total Due:");

        txtTotalValue.setEditable(false);
        txtTotalValue.setToolTipText("The total value of the pawned items.");

        txtPawnAmount.setEditable(false);
        txtPawnAmount.setToolTipText("The amount that the items will be pawned for.");

        txtInterestRate.setEditable(false);
        txtInterestRate.setToolTipText("The interest at which the items will be pawned.");

        txtTotalDue.setEditable(false);
        txtTotalDue.setToolTipText("The total the the customer will have to pay back to reclaime his/her items.");

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(cmdResetForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(cmdNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdCancel))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNoOfItems)
                            .addComponent(lblTotalValue)
                            .addComponent(lblPawnAmount)
                            .addComponent(lblInterestRate)
                            .addComponent(lblInterestDue)
                            .addComponent(lblTotalDue)
                            .addComponent(lblRecievedDate)
                            .addComponent(lblCustID)
                            .addComponent(lblCustName)
                            .addComponent(lblDueDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calDueDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInterestDue)
                            .addComponent(txtNoOfItems)
                            .addComponent(txtCustID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCustName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalValue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPawnAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInterestRate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalDue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calRecievedDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(calRecievedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecievedDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(calDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDueDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoOfItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPawnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPawnAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterestRate)
                    .addComponent(txtInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterestDue)
                    .addComponent(txtInterestDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDue)
                    .addComponent(txtTotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdNext)
                    .addComponent(cmdResetForm))
                .addContainerGap())
        );

        pawnTabbedPane.addTab("General", new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/user.png")), generalPanel); // NOI18N

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Type", "Value", "Pawn Amount"
            }
        ));
        tblItems.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblItems);
        tblItems.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        cmdCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/cross.png"))); // NOI18N
        cmdCancel1.setText("Cancel");

        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/accept.png"))); // NOI18N
        cmdSave.setText("Save");

        cmdRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/delete.png"))); // NOI18N
        cmdRemove.setText("Remove");

        cmdAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/add.png"))); // NOI18N
        cmdAdd.setText("Add");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemsPanelLayout = new javax.swing.GroupLayout(itemsPanel);
        itemsPanel.setLayout(itemsPanelLayout);
        itemsPanelLayout.setHorizontalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                                .addComponent(cmdSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdCancel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                                .addComponent(cmdAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdRemove)))))
                .addContainerGap())
        );
        itemsPanelLayout.setVerticalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdRemove)
                    .addComponent(cmdAdd))
                .addGap(18, 18, 18)
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel1)
                    .addComponent(cmdSave))
                .addContainerGap())
        );

        pawnTabbedPane.addTab("Items", new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/ruby_add.png")), itemsPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pawnTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pawnTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblCustomersMouseClicked
    {//GEN-HEADEREND:event_tblCustomersMouseClicked
        if (evt.getClickCount() >= 2 && tblCustomers.getSelectedRow() != -1)
        {
            loadCustomerInfo();
        }
    }//GEN-LAST:event_tblCustomersMouseClicked
    
    private void cmdCancel5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdCancel5ActionPerformed
    {//GEN-HEADEREND:event_cmdCancel5ActionPerformed
        Utilities.showCancelScreen(this);
    }//GEN-LAST:event_cmdCancel5ActionPerformed
    
    private void cmdNext5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdNext5ActionPerformed
    {//GEN-HEADEREND:event_cmdNext5ActionPerformed
        if (tblCustomers.getSelectedRow() == -1)
        {
            String message = "Kindly select a customer before proceeding.";
            Utilities.showWarningMessage(rootPane, message);
        }
        else
        {
            loadCustomerInfo();
        }
    }//GEN-LAST:event_cmdNext5ActionPerformed
    
    private void cmdCancelcancel(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdCancelcancel
    {//GEN-HEADEREND:event_cmdCancelcancel
        Utilities.showCancelScreen(this);
    }//GEN-LAST:event_cmdCancelcancel
    
    private void cmdNextnext(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdNextnext
    {//GEN-HEADEREND:event_cmdNextnext
        pawnTabbedPane.setSelectedIndex(pawnTabbedPane.getSelectedIndex() + 1);
    }//GEN-LAST:event_cmdNextnext
    
    private void cmdResetFormActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdResetFormActionPerformed
    {//GEN-HEADEREND:event_cmdResetFormActionPerformed
        remove(pawnTabbedPane);
        initComponents();
        populateLists();
    }//GEN-LAST:event_cmdResetFormActionPerformed
    
    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmdAddActionPerformed
    {//GEN-HEADEREND:event_cmdAddActionPerformed
        FrmPawnItem frmPawnItem = new FrmPawnItem(null, true);
        frmPawnItem.setLocationRelativeTo(this);
        frmPawnItem.setVisible(true);
    }//GEN-LAST:event_cmdAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDueDate;
    private com.toedter.calendar.JDateChooser calRecievedDate;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdCancel1;
    private javax.swing.JButton cmdCancel5;
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdNext5;
    private javax.swing.JButton cmdRemove;
    private javax.swing.JButton cmdResetForm;
    private javax.swing.JButton cmdSave;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private de.javasoft.swing.JYTableScrollPane jYTableScrollPane1;
    private javax.swing.JLabel lblCustID;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblInterestDue;
    private javax.swing.JLabel lblInterestRate;
    private javax.swing.JLabel lblNoOfItems;
    private javax.swing.JLabel lblPawnAmount;
    private javax.swing.JLabel lblRecievedDate;
    private javax.swing.JLabel lblTotalDue;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JTabbedPane pawnTabbedPane;
    private javax.swing.JPanel searchPanel;
    private de.javasoft.swing.JYTable tblCustomers;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtInterestDue;
    private javax.swing.JTextField txtInterestRate;
    private javax.swing.JTextField txtNoOfItems;
    private javax.swing.JTextField txtPawnAmount;
    private javax.swing.JTextField txtTotalDue;
    private javax.swing.JTextField txtTotalValue;
    // End of variables declaration//GEN-END:variables
}
