/************************************************************************/
/* iLoan - Quick Loan Management System                                 */
/* ===========================                                          */
/*                                                                      */
/* Copyright (c) 2011 by Maurice Rogers                                 */
/* http://www.mauricerogers.com                                         */
/************************************************************************/

/*
 * FrmNewPawn.java
 *
 * Created on Dec 28, 2010, 8:45:04 AM
 */
package iloan.pawn;

import iloan.ILoanApp;
import java.util.Calendar;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author mrogers
 */
public class FrmNewPawn extends javax.swing.JInternalFrame
{

    /** Creates new form FrmNewPawn */
    public FrmNewPawn()
    {
        Pawn.newPawn();
        initComponents();
        initializeValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pawnTabbedPane = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        cmdCancel = new javax.swing.JButton();
        cmdNext = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmdSearch = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        pawnPanel = new javax.swing.JPanel();
        lblPawnDate = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        lblTotal_Value = new javax.swing.JLabel();
        lblPawnAmount = new javax.swing.JLabel();
        calPawnDate = new com.toedter.calendar.JDateChooser();
        calDueDate = new com.toedter.calendar.JDateChooser();
        txtTotalValue = new javax.swing.JTextField();
        txtPawnAmount = new javax.swing.JTextField();
        lblInterestRate = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        cmdNext5 = new javax.swing.JButton();
        cmdCancel7 = new javax.swing.JButton();
        itemsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        cmdCancel6 = new javax.swing.JButton();
        cmdRemove = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblTotalValue = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class).getContext().getResourceMap(FrmNewPawn.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setToolTipText(resourceMap.getString("Form.toolTipText")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N

        pawnTabbedPane.setName("pawnTabbedPane"); // NOI18N

        searchPanel.setName("searchPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class).getContext().getActionMap(FrmNewPawn.class, this);
        cmdCancel.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel.setName("cmdCancel"); // NOI18N

        cmdNext.setAction(actionMap.get("next")); // NOI18N
        cmdNext.setName("cmdNext"); // NOI18N

        lblSearch.setText(resourceMap.getString("lblSearch.text")); // NOI18N
        lblSearch.setName("lblSearch"); // NOI18N

        txtSearch.setName("txtSearch"); // NOI18N

        cmdSearch.setAction(actionMap.get("Search")); // NOI18N
        cmdSearch.setName("cmdSearch"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust.  ID", "Name", "DOB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResults.setColumnSelectionAllowed(true);
        tblResults.setName("tblResults"); // NOI18N
        jScrollPane4.setViewportView(tblResults);
        tblResults.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblResults.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblResults.columnModel.title0")); // NOI18N
        tblResults.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblResults.columnModel.title1")); // NOI18N
        tblResults.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblResults.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSearch)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdNext))
                .addContainerGap())
        );

        pawnTabbedPane.addTab(resourceMap.getString("searchPanel.TabConstraints.tabTitle"), resourceMap.getIcon("searchPanel.TabConstraints.tabIcon"), searchPanel); // NOI18N

        pawnPanel.setName("pawnPanel"); // NOI18N

        lblPawnDate.setText(resourceMap.getString("lblPawnDate.text")); // NOI18N
        lblPawnDate.setName("lblPawnDate"); // NOI18N

        lblDueDate.setText(resourceMap.getString("lblDueDate.text")); // NOI18N
        lblDueDate.setName("lblDueDate"); // NOI18N

        lblTotal_Value.setText(resourceMap.getString("lblTotal_Value.text")); // NOI18N
        lblTotal_Value.setName("lblTotal_Value"); // NOI18N

        lblPawnAmount.setText(resourceMap.getString("lblPawnAmount.text")); // NOI18N
        lblPawnAmount.setName("lblPawnAmount"); // NOI18N

        calPawnDate.setName("calPawnDate"); // NOI18N

        calDueDate.setName("calDueDate"); // NOI18N

        txtTotalValue.setEditable(false);
        txtTotalValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalValue.setText(resourceMap.getString("txtTotalValue.text")); // NOI18N
        txtTotalValue.setName("txtTotalValue"); // NOI18N

        txtPawnAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPawnAmount.setText(resourceMap.getString("txtPawnAmount.text")); // NOI18N
        txtPawnAmount.setName("txtPawnAmount"); // NOI18N

        lblInterestRate.setText(resourceMap.getString("lblInterestRate.text")); // NOI18N
        lblInterestRate.setName("lblInterestRate"); // NOI18N

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N

        cmdNext5.setAction(actionMap.get("next")); // NOI18N
        cmdNext5.setName("cmdNext5"); // NOI18N

        cmdCancel7.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel7.setName("cmdCancel7"); // NOI18N

        javax.swing.GroupLayout pawnPanelLayout = new javax.swing.GroupLayout(pawnPanel);
        pawnPanel.setLayout(pawnPanelLayout);
        pawnPanelLayout.setHorizontalGroup(
            pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pawnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pawnPanelLayout.createSequentialGroup()
                        .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPawnAmount)
                            .addComponent(lblPawnDate)
                            .addComponent(lblDueDate)
                            .addComponent(lblInterestRate)
                            .addComponent(lblTotal_Value))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(calDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(calPawnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(txtPawnAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pawnPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext5)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel7)))
                .addContainerGap())
        );
        pawnPanelLayout.setVerticalGroup(
            pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pawnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calPawnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPawnDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDueDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInterestRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPawnAmount)
                    .addComponent(txtPawnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(pawnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel7)
                    .addComponent(cmdNext5))
                .addContainerGap())
        );

        pawnTabbedPane.addTab(resourceMap.getString("pawnPanel.TabConstraints.tabTitle"), resourceMap.getIcon("pawnPanel.TabConstraints.tabIcon"), pawnPanel); // NOI18N

        itemsPanel.setName("itemsPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Description", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.setName("tblItems"); // NOI18N
        tblItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblItems);
        tblItems.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblItems.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblItems.columnModel.title1")); // NOI18N
        tblItems.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblItems.columnModel.title2")); // NOI18N
        tblItems.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblItems.columnModel.title3")); // NOI18N

        cmdCancel6.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel6.setName("cmdCancel6"); // NOI18N

        cmdRemove.setAction(actionMap.get("removeItem")); // NOI18N
        cmdRemove.setIcon(resourceMap.getIcon("cmdRemove.icon")); // NOI18N
        cmdRemove.setText(resourceMap.getString("cmdRemove.text")); // NOI18N
        cmdRemove.setName("cmdRemove"); // NOI18N

        cmdAdd.setAction(actionMap.get("loadAddItem")); // NOI18N
        cmdAdd.setIcon(resourceMap.getIcon("cmdAdd.icon")); // NOI18N
        cmdAdd.setText(resourceMap.getString("cmdAdd.text")); // NOI18N
        cmdAdd.setName("cmdAdd"); // NOI18N

        cmdEdit.setAction(actionMap.get("loadEditItem")); // NOI18N
        cmdEdit.setIcon(resourceMap.getIcon("cmdEdit.icon")); // NOI18N
        cmdEdit.setText(resourceMap.getString("cmdEdit.text")); // NOI18N
        cmdEdit.setName("cmdEdit"); // NOI18N

        jButton1.setAction(actionMap.get("savePawn")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        lblTotalValue.setText(resourceMap.getString("lblTotalValue.text")); // NOI18N
        lblTotalValue.setName("lblTotalValue"); // NOI18N

        javax.swing.GroupLayout itemsPanelLayout = new javax.swing.GroupLayout(itemsPanel);
        itemsPanel.setLayout(itemsPanelLayout);
        itemsPanelLayout.setHorizontalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                        .addComponent(lblTotalValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(cmdAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdRemove))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                .addContainerGap())
        );
        itemsPanelLayout.setVerticalGroup(
            itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdRemove)
                    .addComponent(cmdEdit)
                    .addComponent(cmdAdd)
                    .addComponent(lblTotalValue))
                .addGap(18, 18, 18)
                .addGroup(itemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel6)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pawnTabbedPane.addTab(resourceMap.getString("itemsPanel.TabConstraints.tabTitle"), resourceMap.getIcon("itemsPanel.TabConstraints.tabIcon"), itemsPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pawnTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pawnTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void cancel()
    {
        int response = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to cancel?", "iLoan", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    private void initializeValues()
    {
        Calendar cal = Calendar.getInstance();
        calPawnDate.setDate(cal.getTime());
        cal.add(Calendar.DATE, 30);
        calDueDate.setDate(cal.getTime());
    }

    @Action
    public void next()
    {
        pawnTabbedPane.setSelectedIndex(pawnTabbedPane.getSelectedIndex() + 1);
    }

    @Action
    public Task Search()
    {
        return new SearchTask(org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class));
    }

    private class SearchTask extends org.jdesktop.application.Task<Object, Void>
    {

        SearchTask(org.jdesktop.application.Application app)
        {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SearchTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground()
        {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result)
        {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }

    @Action
    public Task savePawn()
    {
        return new SavePawnTask(org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class));
    }

    private class SavePawnTask extends org.jdesktop.application.Task<Object, Void>
    {

        SavePawnTask(org.jdesktop.application.Application app)
        {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SavePawnTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground()
        {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result)
        {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }

    @Action
    public void loadAddItem()
    {
        FrmItem addItem = null;
        addItem = new FrmItem(ILoanApp.getApplication().getMainFrame(), true, tblItems);
        addItem.setVisible(true);
        lblTotalValue.setText("Total Value: " + Pawn.getFormattedValueTotal());
        txtTotalValue.setText(Pawn.getFormattedValueTotal());
    }

    @Action
    public void removeItem()
    {
        int selectedItem = tblItems.getSelectedRow();
        if (selectedItem != -1)
        {
            String message = "Are you sure you want to remove that item from the list";
            int response = JOptionPane.showConfirmDialog(rootPane, message, "iLoan", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION)
            {
                Pawn.removeItem(selectedItem);
                Pawn.loadPawnItems(tblItems);
                lblTotalValue.setText("Total Value: " + Pawn.getFormattedValueTotal());
                lblTotal_Value.setText(Pawn.getFormattedValueTotal());
            }
        }
        else
        {
            String message = "Kindly select an item before trying to remove it.";
            JOptionPane.showMessageDialog(rootPane, message, "iLoan", JOptionPane.WARNING_MESSAGE);
        }
    }

    @Action
    public void loadEditItem()
    {

        int selectedItem = tblItems.getSelectedRow();
        if (selectedItem != -1)
        {
            FrmItem addItem = null;
            addItem = new FrmItem(ILoanApp.getApplication().getMainFrame(), true, tblItems, true, selectedItem);
            addItem.setVisible(true);
            lblTotalValue.setText("Total Value: " + Pawn.getFormattedValueTotal());
            lblTotal_Value.setText(Pawn.getFormattedValueTotal());
        }
        else
        {
            String message = "Kindly select an item before trying to edit it.";
            JOptionPane.showMessageDialog(rootPane, message, "iLoan", JOptionPane.WARNING_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDueDate;
    private com.toedter.calendar.JDateChooser calPawnDate;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdCancel6;
    private javax.swing.JButton cmdCancel7;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdNext5;
    private javax.swing.JButton cmdRemove;
    private javax.swing.JButton cmdSearch;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblInterestRate;
    private javax.swing.JLabel lblPawnAmount;
    private javax.swing.JLabel lblPawnDate;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblTotal_Value;
    private javax.swing.JPanel pawnPanel;
    private javax.swing.JTabbedPane pawnTabbedPane;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextField txtPawnAmount;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalValue;
    // End of variables declaration//GEN-END:variables
}
