/************************************************************************/
/* iLoan - Quick Loan Management System                                 */
/* ===========================                                          */
/*                                                                      */
/* Copyright (c) 2011 by Maurice Rogers                                 */
/* http://www.mauricerogers.com                                         */
/************************************************************************/

/*
 * FrmNewCustomer.java
 *
 * Created on Sep 1, 2010, 12:33:15 AM
 */
package iloan.customer;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author mrogers
 */
public class FrmEditCustomer extends javax.swing.JInternalFrame
{

    File selectedFile = null;

    /** Creates new form FrmNewCustomer */
    public FrmEditCustomer()
    {
        initComponents();
        Customer.loadidTypes(cmbIDType);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerTabbedPane = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        cmdCancel5 = new javax.swing.JButton();
        cmdNext4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        generalPanel = new javax.swing.JPanel();
        lblDOB = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        cmbSex = new javax.swing.JComboBox();
        calDOB = new com.toedter.calendar.JDateChooser();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblOtherName = new javax.swing.JLabel();
        txtOtherNames = new javax.swing.JTextField();
        txtTitle = new javax.swing.JLabel();
        cmbSalutation = new javax.swing.JComboBox();
        cmdCancel1 = new javax.swing.JButton();
        cmdNext1 = new javax.swing.JButton();
        personalPanel = new javax.swing.JPanel();
        lblHomePhone = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHomeAddress = new javax.swing.JTextArea();
        txtHomeMobile = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        cmdNext2 = new javax.swing.JButton();
        cmdCancel2 = new javax.swing.JButton();
        workPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtWorkAddress = new javax.swing.JTextArea();
        txtWorkMobile = new javax.swing.JTextField();
        txtWorkPhone = new javax.swing.JTextField();
        lblworkAddress = new javax.swing.JLabel();
        lblWorkMobile = new javax.swing.JLabel();
        lblWorkPhone = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        cmdNext3 = new javax.swing.JButton();
        cmdCancel3 = new javax.swing.JButton();
        identificationPanel = new javax.swing.JPanel();
        lblPicture = new javax.swing.JLabel();
        txtPicture = new javax.swing.JTextField();
        cmdBrowse = new javax.swing.JButton();
        lblIdType = new javax.swing.JLabel();
        cmbIDType = new javax.swing.JComboBox();
        lblIDNumber = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cmdSave = new javax.swing.JButton();
        cmdCancel4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class).getContext().getResourceMap(FrmEditCustomer.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setToolTipText(resourceMap.getString("Form.toolTipText")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N

        customerTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        customerTabbedPane.setName("customerTabbedPane"); // NOI18N

        searchPanel.setName("searchPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class).getContext().getActionMap(FrmEditCustomer.class, this);
        cmdCancel5.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel5.setName("cmdCancel5"); // NOI18N

        cmdNext4.setAction(actionMap.get("next")); // NOI18N
        cmdNext4.setName("cmdNext4"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jButton1.setAction(actionMap.get("search")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust.  ID", "Name", "DOB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane4.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable1.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext4)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel5))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel5)
                    .addComponent(cmdNext4))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("searchPanel.TabConstraints.tabTitle"), resourceMap.getIcon("searchPanel.TabConstraints.tabIcon"), searchPanel); // NOI18N

        generalPanel.setName("generalPanel"); // NOI18N

        lblDOB.setText(resourceMap.getString("lblDOB.text")); // NOI18N
        lblDOB.setName("lblDOB"); // NOI18N

        lblSex.setText(resourceMap.getString("lblSex.text")); // NOI18N
        lblSex.setName("lblSex"); // NOI18N

        lblNotes.setText(resourceMap.getString("lblNotes.text")); // NOI18N
        lblNotes.setName("lblNotes"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        txtNotes.setToolTipText(resourceMap.getString("txtNotes.toolTipText")); // NOI18N
        txtNotes.setName("txtNotes"); // NOI18N
        jScrollPane2.setViewportView(txtNotes);

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cmbSex.setToolTipText(resourceMap.getString("cmbSex.toolTipText")); // NOI18N
        cmbSex.setName("cmbSex"); // NOI18N

        calDOB.setToolTipText(resourceMap.getString("calDOB.toolTipText")); // NOI18N
        calDOB.setName("calDOB"); // NOI18N

        lblFirstName.setFont(resourceMap.getFont("lblFirstName.font")); // NOI18N
        lblFirstName.setText(resourceMap.getString("lblFirstName.text")); // NOI18N
        lblFirstName.setName("lblFirstName"); // NOI18N

        txtFirstName.setToolTipText(resourceMap.getString("txtFirstName.toolTipText")); // NOI18N
        txtFirstName.setName("txtFirstName"); // NOI18N

        lblLastName.setFont(resourceMap.getFont("lblLastName.font")); // NOI18N
        lblLastName.setText(resourceMap.getString("lblLastName.text")); // NOI18N
        lblLastName.setName("lblLastName"); // NOI18N

        txtLastName.setToolTipText(resourceMap.getString("txtLastName.toolTipText")); // NOI18N
        txtLastName.setName("txtLastName"); // NOI18N

        lblOtherName.setText(resourceMap.getString("lblOtherName.text")); // NOI18N
        lblOtherName.setName("lblOtherName"); // NOI18N

        txtOtherNames.setToolTipText(resourceMap.getString("txtOtherNames.toolTipText")); // NOI18N
        txtOtherNames.setName("txtOtherNames"); // NOI18N

        txtTitle.setText(resourceMap.getString("txtTitle.text")); // NOI18N
        txtTitle.setName("txtTitle"); // NOI18N

        cmbSalutation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Ms.", "Mrs.", "Dr.", "Sir.", "Lady.", "" }));
        cmbSalutation.setToolTipText(resourceMap.getString("cmbSalutation.toolTipText")); // NOI18N
        cmbSalutation.setName("cmbSalutation"); // NOI18N

        cmdCancel1.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel1.setText(resourceMap.getString("cmdCancel1.text")); // NOI18N
        cmdCancel1.setName("cmdCancel1"); // NOI18N

        cmdNext1.setAction(actionMap.get("next")); // NOI18N
        cmdNext1.setText(resourceMap.getString("cmdNext1.text")); // NOI18N
        cmdNext1.setName("cmdNext1"); // NOI18N

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOtherName)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName)
                            .addComponent(lblDOB)
                            .addComponent(lblSex)
                            .addComponent(txtTitle)
                            .addComponent(lblNotes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(cmbSex, 0, 276, Short.MAX_VALUE)
                            .addComponent(calDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtOtherNames, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(cmbSalutation, 0, 276, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext1)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel1)))
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle)
                    .addComponent(cmbSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOtherName)
                    .addComponent(txtOtherNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDOB)
                    .addComponent(calDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotes)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel1)
                    .addComponent(cmdNext1))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("generalPanel.TabConstraints.tabTitle"), resourceMap.getIcon("generalPanel.TabConstraints.tabIcon"), generalPanel); // NOI18N

        personalPanel.setName("personalPanel"); // NOI18N

        lblHomePhone.setText(resourceMap.getString("lblHomePhone.text")); // NOI18N
        lblHomePhone.setName("lblHomePhone"); // NOI18N

        lblMobile.setText(resourceMap.getString("lblMobile.text")); // NOI18N
        lblMobile.setName("lblMobile"); // NOI18N

        lblAddress.setFont(resourceMap.getFont("lblAddress.font")); // NOI18N
        lblAddress.setText(resourceMap.getString("lblAddress.text")); // NOI18N
        lblAddress.setName("lblAddress"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtHomeAddress.setColumns(20);
        txtHomeAddress.setRows(5);
        txtHomeAddress.setToolTipText(resourceMap.getString("txtHomeAddress.toolTipText")); // NOI18N
        txtHomeAddress.setName("txtHomeAddress"); // NOI18N
        jScrollPane1.setViewportView(txtHomeAddress);

        txtHomeMobile.setText(resourceMap.getString("txtHomeMobile.text")); // NOI18N
        txtHomeMobile.setToolTipText(resourceMap.getString("txtHomeMobile.toolTipText")); // NOI18N
        txtHomeMobile.setName("txtHomeMobile"); // NOI18N

        txtHomePhone.setText(resourceMap.getString("txtHomePhone.text")); // NOI18N
        txtHomePhone.setToolTipText(resourceMap.getString("txtHomePhone.toolTipText")); // NOI18N
        txtHomePhone.setName("txtHomePhone"); // NOI18N

        cmdNext2.setAction(actionMap.get("next")); // NOI18N
        cmdNext2.setName("cmdNext2"); // NOI18N

        cmdCancel2.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel2.setName("cmdCancel2"); // NOI18N

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalPanelLayout.createSequentialGroup()
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(lblMobile)
                            .addComponent(lblHomePhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHomeMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtHomePhone, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext2)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel2)))
                .addContainerGap())
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomePhone)
                    .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobile)
                    .addComponent(txtHomeMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel2)
                    .addComponent(cmdNext2))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("personalPanel.TabConstraints.tabTitle"), resourceMap.getIcon("personalPanel.TabConstraints.tabIcon"), personalPanel); // NOI18N

        workPanel.setName("workPanel"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        txtWorkAddress.setColumns(20);
        txtWorkAddress.setRows(5);
        txtWorkAddress.setToolTipText(resourceMap.getString("txtWorkAddress.toolTipText")); // NOI18N
        txtWorkAddress.setName("txtWorkAddress"); // NOI18N
        jScrollPane3.setViewportView(txtWorkAddress);

        txtWorkMobile.setToolTipText(resourceMap.getString("txtWorkMobile.toolTipText")); // NOI18N
        txtWorkMobile.setName("txtWorkMobile"); // NOI18N

        txtWorkPhone.setToolTipText(resourceMap.getString("txtWorkPhone.toolTipText")); // NOI18N
        txtWorkPhone.setName("txtWorkPhone"); // NOI18N

        lblworkAddress.setText(resourceMap.getString("lblworkAddress.text")); // NOI18N
        lblworkAddress.setName("lblworkAddress"); // NOI18N

        lblWorkMobile.setText(resourceMap.getString("lblWorkMobile.text")); // NOI18N
        lblWorkMobile.setName("lblWorkMobile"); // NOI18N

        lblWorkPhone.setText(resourceMap.getString("lblWorkPhone.text")); // NOI18N
        lblWorkPhone.setName("lblWorkPhone"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setToolTipText(resourceMap.getString("jTextField5.toolTipText")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N

        cmdNext3.setAction(actionMap.get("next")); // NOI18N
        cmdNext3.setName("cmdNext3"); // NOI18N

        cmdCancel3.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel3.setName("cmdCancel3"); // NOI18N

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblWorkPhone)
                            .addComponent(lblWorkMobile)
                            .addComponent(lblworkAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtWorkMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtWorkPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext3)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel3)))
                .addContainerGap())
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkMobile)
                    .addComponent(txtWorkMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblworkAddress)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdCancel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdNext3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("workPanel.TabConstraints.tabTitle"), resourceMap.getIcon("workPanel.TabConstraints.tabIcon"), workPanel); // NOI18N

        identificationPanel.setName("identificationPanel"); // NOI18N

        lblPicture.setFont(resourceMap.getFont("lblPicture.font")); // NOI18N
        lblPicture.setText(resourceMap.getString("lblPicture.text")); // NOI18N
        lblPicture.setName("lblPicture"); // NOI18N

        txtPicture.setEditable(false);
        txtPicture.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPicture.setToolTipText(resourceMap.getString("txtPicture.toolTipText")); // NOI18N
        txtPicture.setName("txtPicture"); // NOI18N

        cmdBrowse.setAction(actionMap.get("browse")); // NOI18N
        cmdBrowse.setName("cmdBrowse"); // NOI18N

        lblIdType.setFont(resourceMap.getFont("lblIdType.font")); // NOI18N
        lblIdType.setText(resourceMap.getString("lblIdType.text")); // NOI18N
        lblIdType.setName("lblIdType"); // NOI18N

        cmbIDType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIDType.setToolTipText(resourceMap.getString("cmbIDType.toolTipText")); // NOI18N
        cmbIDType.setName("cmbIDType"); // NOI18N

        lblIDNumber.setFont(resourceMap.getFont("lblIDNumber.font")); // NOI18N
        lblIDNumber.setText(resourceMap.getString("lblIDNumber.text")); // NOI18N
        lblIDNumber.setName("lblIDNumber"); // NOI18N

        txtIDNumber.setToolTipText(resourceMap.getString("txtIDNumber.toolTipText")); // NOI18N
        txtIDNumber.setName("txtIDNumber"); // NOI18N

        lblCustomerID.setText(resourceMap.getString("lblCustomerID.text")); // NOI18N
        lblCustomerID.setName("lblCustomerID"); // NOI18N

        txtCustomerID.setEditable(false);
        txtCustomerID.setToolTipText(resourceMap.getString("txtCustomerID.toolTipText")); // NOI18N
        txtCustomerID.setName("txtCustomerID"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        cmdSave.setAction(actionMap.get("save")); // NOI18N
        cmdSave.setName("cmdSave"); // NOI18N

        cmdCancel4.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel4.setName("cmdCancel4"); // NOI18N

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addGroup(identificationPanelLayout.createSequentialGroup()
                                .addComponent(lblCustomerID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identificationPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdBrowse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(identificationPanelLayout.createSequentialGroup()
                                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDNumber)
                                    .addComponent(lblIdType)
                                    .addComponent(lblPicture))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(identificationPanelLayout.createSequentialGroup()
                                        .addComponent(txtPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addComponent(cmbIDType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 277, Short.MAX_VALUE)
                                    .addComponent(txtIDNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identificationPanelLayout.createSequentialGroup()
                        .addContainerGap(228, Short.MAX_VALUE)
                        .addComponent(cmdSave)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel4)))
                .addContainerGap())
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerID)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdType)
                    .addComponent(cmbIDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDNumber)
                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(txtPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel4)
                    .addComponent(cmdSave))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("identificationPanel.TabConstraints.tabTitle"), resourceMap.getIcon("identificationPanel.TabConstraints.tabIcon"), identificationPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void cancel()
    {
        int response = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to cancel?", "iLoan", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    @Action
    public void next()
    {
        customerTabbedPane.setSelectedIndex(customerTabbedPane.getSelectedIndex() + 1);
    }

    @Action
    public Task save()
    {
        return new SaveTask(org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class));
    }

    private class SaveTask extends org.jdesktop.application.Task<Object, Void>
    {

        SaveTask(org.jdesktop.application.Application app)
        {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SaveTask fields, here.
            super(app);
        }

        @Override
        protected Object doInBackground()
        {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result)
        {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }

    @Action
    public void clearForm()
    {
    }

    @Action
    public void browse()
    {
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showOpenDialog(rootPane);
        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                selectedFile = fc.getSelectedFile();
                txtPicture.setText(selectedFile.getCanonicalPath());
            }
            catch (IOException ex)
            {
                Logger.getLogger(FrmEditCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Action
    public Task search()
    {
        return new SearchTask(org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class));
    }

    private class SearchTask extends org.jdesktop.application.Task<Object, Void> {
        SearchTask(org.jdesktop.application.Application app) {
            // Runs on the EDT.  Copy GUI state that
            // doInBackground() depends on from parameters
            // to SearchTask fields, here.
            super(app);
        }
        @Override protected Object doInBackground() {
            // Your Task's code here.  This method runs
            // on a background thread, so don't reference
            // the Swing GUI from here.
            return null;  // return your result
        }
        @Override protected void succeeded(Object result) {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDOB;
    private javax.swing.JComboBox cmbIDType;
    private javax.swing.JComboBox cmbSalutation;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JButton cmdCancel1;
    private javax.swing.JButton cmdCancel2;
    private javax.swing.JButton cmdCancel3;
    private javax.swing.JButton cmdCancel4;
    private javax.swing.JButton cmdCancel5;
    private javax.swing.JButton cmdNext1;
    private javax.swing.JButton cmdNext2;
    private javax.swing.JButton cmdNext3;
    private javax.swing.JButton cmdNext4;
    private javax.swing.JButton cmdSave;
    private javax.swing.JTabbedPane customerTabbedPane;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomePhone;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblIdType;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblOtherName;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblWorkMobile;
    private javax.swing.JLabel lblWorkPhone;
    private javax.swing.JLabel lblworkAddress;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextArea txtHomeAddress;
    private javax.swing.JTextField txtHomeMobile;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtOtherNames;
    private javax.swing.JTextField txtPicture;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextArea txtWorkAddress;
    private javax.swing.JTextField txtWorkMobile;
    private javax.swing.JTextField txtWorkPhone;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
