/************************************************************************/
/* iLoan - Quick Loan Management System                                 */
/* ===========================                                          */
/*                                                                      */
/* Copyright (c) 2011 by Maurice Rogers                                 */
/* http://www.mauricerogers.com                                         */
/************************************************************************/

/*
 * FrmNewCustomer.java
 *
 * Created on Sep 1, 2010, 12:33:15 AM
 */
package iloan.customer;

import iloan.kernel.Utilities;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author mrogers
 */
public class FrmNewCustomer extends javax.swing.JInternalFrame
{

    File selectedFile = null;

    /** Creates new form FrmNewCustomer */
    public FrmNewCustomer()
    {
        initComponents();
        Customer.loadidTypes(cmbIDType);
        Customer.loadOccupationList(cmbOccupation);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerTabbedPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        lblDOB = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        cmbSex = new javax.swing.JComboBox();
        calDOB = new com.toedter.calendar.JDateChooser();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblOtherName = new javax.swing.JLabel();
        txtOtherNames = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        cmbSalutation = new javax.swing.JComboBox();
        cmdCancel1 = new javax.swing.JButton();
        cmdNext1 = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        personalPanel = new javax.swing.JPanel();
        lblHomePhone = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHomeAddress = new javax.swing.JTextArea();
        txtHomeMobile = new javax.swing.JTextField();
        txtHomePhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        cmdNext2 = new javax.swing.JButton();
        cmdCancel2 = new javax.swing.JButton();
        workPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtWorkAddress = new javax.swing.JTextArea();
        txtWorkMobile = new javax.swing.JTextField();
        txtWorkPhone = new javax.swing.JTextField();
        lblworkAddress = new javax.swing.JLabel();
        lblWorkMobile = new javax.swing.JLabel();
        lblWorkPhone = new javax.swing.JLabel();
        lblWorkplcae = new javax.swing.JLabel();
        txtWorkPlace = new javax.swing.JTextField();
        cmdNext3 = new javax.swing.JButton();
        cmdCancel3 = new javax.swing.JButton();
        lblOccupation = new javax.swing.JLabel();
        cmbOccupation = new javax.swing.JComboBox();
        txtWorkEmail = new javax.swing.JTextField();
        lblWorkEmail = new javax.swing.JLabel();
        identificationPanel = new javax.swing.JPanel();
        lblPicture = new javax.swing.JLabel();
        txtPicture = new javax.swing.JTextField();
        cmdBrowse = new javax.swing.JButton();
        lblIdType = new javax.swing.JLabel();
        cmbIDType = new javax.swing.JComboBox();
        lblIDNumber = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        cmdSave = new javax.swing.JButton();
        cmdCancel4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class).getContext().getResourceMap(FrmNewCustomer.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setToolTipText(resourceMap.getString("Form.toolTipText")); // NOI18N
        setFrameIcon(resourceMap.getIcon("Form.frameIcon")); // NOI18N
        setName("Form"); // NOI18N

        customerTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        customerTabbedPane.setName("customerTabbedPane"); // NOI18N

        generalPanel.setName("generalPanel"); // NOI18N

        lblDOB.setFont(resourceMap.getFont("lblDOB.font")); // NOI18N
        lblDOB.setText(resourceMap.getString("lblDOB.text")); // NOI18N
        lblDOB.setName("lblDOB"); // NOI18N

        lblSex.setText(resourceMap.getString("lblSex.text")); // NOI18N
        lblSex.setName("lblSex"); // NOI18N

        lblNotes.setText(resourceMap.getString("lblNotes.text")); // NOI18N
        lblNotes.setName("lblNotes"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        txtNotes.setToolTipText(resourceMap.getString("txtNotes.toolTipText")); // NOI18N
        txtNotes.setName("txtNotes"); // NOI18N
        jScrollPane2.setViewportView(txtNotes);

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cmbSex.setToolTipText(resourceMap.getString("cmbSex.toolTipText")); // NOI18N
        cmbSex.setName("cmbSex"); // NOI18N

        calDOB.setToolTipText(resourceMap.getString("calDOB.toolTipText")); // NOI18N
        calDOB.setName("calDOB"); // NOI18N

        lblFirstName.setFont(resourceMap.getFont("lblFirstName.font")); // NOI18N
        lblFirstName.setText(resourceMap.getString("lblFirstName.text")); // NOI18N
        lblFirstName.setName("lblFirstName"); // NOI18N

        txtFirstName.setToolTipText(resourceMap.getString("txtFirstName.toolTipText")); // NOI18N
        txtFirstName.setName("txtFirstName"); // NOI18N

        lblLastName.setFont(resourceMap.getFont("lblLastName.font")); // NOI18N
        lblLastName.setText(resourceMap.getString("lblLastName.text")); // NOI18N
        lblLastName.setName("lblLastName"); // NOI18N

        txtLastName.setToolTipText(resourceMap.getString("txtLastName.toolTipText")); // NOI18N
        txtLastName.setName("txtLastName"); // NOI18N

        lblOtherName.setText(resourceMap.getString("lblOtherName.text")); // NOI18N
        lblOtherName.setName("lblOtherName"); // NOI18N

        txtOtherNames.setToolTipText(resourceMap.getString("txtOtherNames.toolTipText")); // NOI18N
        txtOtherNames.setName("txtOtherNames"); // NOI18N

        lblTitle.setText(resourceMap.getString("lblTitle.text")); // NOI18N
        lblTitle.setName("lblTitle"); // NOI18N

        cmbSalutation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Ms.", "Mrs.", "Dr.", "Sir.", "Lady.", "" }));
        cmbSalutation.setToolTipText(resourceMap.getString("cmbSalutation.toolTipText")); // NOI18N
        cmbSalutation.setName("cmbSalutation"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class).getContext().getActionMap(FrmNewCustomer.class, this);
        cmdCancel1.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel1.setText(resourceMap.getString("cmdCancel1.text")); // NOI18N
        cmdCancel1.setName("cmdCancel1"); // NOI18N

        cmdNext1.setAction(actionMap.get("next")); // NOI18N
        cmdNext1.setText(resourceMap.getString("cmdNext1.text")); // NOI18N
        cmdNext1.setName("cmdNext1"); // NOI18N

        cmdReset.setAction(actionMap.get("clearForm")); // NOI18N
        cmdReset.setText(resourceMap.getString("cmdReset.text")); // NOI18N
        cmdReset.setName("cmdReset"); // NOI18N

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOtherName)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName)
                            .addComponent(lblDOB)
                            .addComponent(lblSex)
                            .addComponent(lblTitle)
                            .addComponent(lblNotes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(cmbSex, 0, 276, Short.MAX_VALUE)
                            .addComponent(calDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(txtOtherNames, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(cmbSalutation, 0, 276, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalPanelLayout.createSequentialGroup()
                        .addComponent(cmdReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(cmdNext1)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel1)))
                .addContainerGap())
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(cmbSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOtherName)
                    .addComponent(txtOtherNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDOB)
                    .addComponent(calDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotes)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel1)
                    .addComponent(cmdNext1)
                    .addComponent(cmdReset))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("generalPanel.TabConstraints.tabTitle"), resourceMap.getIcon("generalPanel.TabConstraints.tabIcon"), generalPanel); // NOI18N

        personalPanel.setName("personalPanel"); // NOI18N

        lblHomePhone.setText(resourceMap.getString("lblHomePhone.text")); // NOI18N
        lblHomePhone.setName("lblHomePhone"); // NOI18N

        lblMobile.setText(resourceMap.getString("lblMobile.text")); // NOI18N
        lblMobile.setName("lblMobile"); // NOI18N

        lblAddress.setFont(resourceMap.getFont("lblAddress.font")); // NOI18N
        lblAddress.setText(resourceMap.getString("lblAddress.text")); // NOI18N
        lblAddress.setName("lblAddress"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtHomeAddress.setColumns(20);
        txtHomeAddress.setRows(5);
        txtHomeAddress.setToolTipText(resourceMap.getString("txtHomeAddress.toolTipText")); // NOI18N
        txtHomeAddress.setName("txtHomeAddress"); // NOI18N
        jScrollPane1.setViewportView(txtHomeAddress);

        txtHomeMobile.setText(resourceMap.getString("txtHomeMobile.text")); // NOI18N
        txtHomeMobile.setToolTipText(resourceMap.getString("txtHomeMobile.toolTipText")); // NOI18N
        txtHomeMobile.setName("txtHomeMobile"); // NOI18N

        txtHomePhone.setText(resourceMap.getString("txtHomePhone.text")); // NOI18N
        txtHomePhone.setToolTipText(resourceMap.getString("txtHomePhone.toolTipText")); // NOI18N
        txtHomePhone.setName("txtHomePhone"); // NOI18N

        txtEmail.setText(resourceMap.getString("txtEmail.text")); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N

        lblEmail.setText(resourceMap.getString("lblEmail.text")); // NOI18N
        lblEmail.setName("lblEmail"); // NOI18N

        cmdNext2.setAction(actionMap.get("next")); // NOI18N
        cmdNext2.setName("cmdNext2"); // NOI18N

        cmdCancel2.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel2.setName("cmdCancel2"); // NOI18N

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalPanelLayout.createSequentialGroup()
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(lblMobile)
                            .addComponent(lblHomePhone)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHomeMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtHomePhone, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext2)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel2)))
                .addContainerGap())
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomePhone)
                    .addComponent(txtHomePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobile)
                    .addComponent(txtHomeMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel2)
                    .addComponent(cmdNext2))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("personalPanel.TabConstraints.tabTitle"), resourceMap.getIcon("personalPanel.TabConstraints.tabIcon"), personalPanel); // NOI18N

        workPanel.setName("workPanel"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        txtWorkAddress.setColumns(20);
        txtWorkAddress.setRows(5);
        txtWorkAddress.setToolTipText(resourceMap.getString("txtWorkAddress.toolTipText")); // NOI18N
        txtWorkAddress.setName("txtWorkAddress"); // NOI18N
        jScrollPane3.setViewportView(txtWorkAddress);

        txtWorkMobile.setToolTipText(resourceMap.getString("txtWorkMobile.toolTipText")); // NOI18N
        txtWorkMobile.setName("txtWorkMobile"); // NOI18N

        txtWorkPhone.setToolTipText(resourceMap.getString("txtWorkPhone.toolTipText")); // NOI18N
        txtWorkPhone.setName("txtWorkPhone"); // NOI18N

        lblworkAddress.setText(resourceMap.getString("lblworkAddress.text")); // NOI18N
        lblworkAddress.setName("lblworkAddress"); // NOI18N

        lblWorkMobile.setText(resourceMap.getString("lblWorkMobile.text")); // NOI18N
        lblWorkMobile.setName("lblWorkMobile"); // NOI18N

        lblWorkPhone.setText(resourceMap.getString("lblWorkPhone.text")); // NOI18N
        lblWorkPhone.setName("lblWorkPhone"); // NOI18N

        lblWorkplcae.setText(resourceMap.getString("lblWorkplcae.text")); // NOI18N
        lblWorkplcae.setName("lblWorkplcae"); // NOI18N

        txtWorkPlace.setText(resourceMap.getString("txtWorkPlace.text")); // NOI18N
        txtWorkPlace.setToolTipText(resourceMap.getString("txtWorkPlace.toolTipText")); // NOI18N
        txtWorkPlace.setName("txtWorkPlace"); // NOI18N

        cmdNext3.setAction(actionMap.get("next")); // NOI18N
        cmdNext3.setName("cmdNext3"); // NOI18N

        cmdCancel3.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel3.setName("cmdCancel3"); // NOI18N

        lblOccupation.setText(resourceMap.getString("lblOccupation.text")); // NOI18N
        lblOccupation.setName("lblOccupation"); // NOI18N

        cmbOccupation.setName("cmbOccupation"); // NOI18N

        txtWorkEmail.setName("txtWorkEmail"); // NOI18N

        lblWorkEmail.setText(resourceMap.getString("lblWorkEmail.text")); // NOI18N
        lblWorkEmail.setName("lblWorkEmail"); // NOI18N

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanelLayout.createSequentialGroup()
                        .addComponent(cmdNext3)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel3))
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOccupation)
                            .addComponent(lblWorkplcae)
                            .addComponent(lblWorkPhone)
                            .addComponent(lblWorkMobile)
                            .addComponent(lblworkAddress)
                            .addComponent(lblWorkEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWorkEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(txtWorkMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(txtWorkPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(txtWorkPlace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(cmbOccupation, 0, 287, Short.MAX_VALUE))))
                .addContainerGap())
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOccupation)
                    .addComponent(cmbOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkplcae)
                    .addComponent(txtWorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkMobile)
                    .addComponent(txtWorkMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblworkAddress)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdCancel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdNext3))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("workPanel.TabConstraints.tabTitle"), resourceMap.getIcon("workPanel.TabConstraints.tabIcon"), workPanel); // NOI18N

        identificationPanel.setName("identificationPanel"); // NOI18N

        lblPicture.setFont(resourceMap.getFont("lblPicture.font")); // NOI18N
        lblPicture.setText(resourceMap.getString("lblPicture.text")); // NOI18N
        lblPicture.setName("lblPicture"); // NOI18N

        txtPicture.setEditable(false);
        txtPicture.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPicture.setToolTipText(resourceMap.getString("txtPicture.toolTipText")); // NOI18N
        txtPicture.setName("txtPicture"); // NOI18N

        cmdBrowse.setAction(actionMap.get("browse")); // NOI18N
        cmdBrowse.setName("cmdBrowse"); // NOI18N

        lblIdType.setFont(resourceMap.getFont("lblIdType.font")); // NOI18N
        lblIdType.setText(resourceMap.getString("lblIdType.text")); // NOI18N
        lblIdType.setName("lblIdType"); // NOI18N

        cmbIDType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIDType.setToolTipText(resourceMap.getString("cmbIDType.toolTipText")); // NOI18N
        cmbIDType.setName("cmbIDType"); // NOI18N

        lblIDNumber.setFont(resourceMap.getFont("lblIDNumber.font")); // NOI18N
        lblIDNumber.setText(resourceMap.getString("lblIDNumber.text")); // NOI18N
        lblIDNumber.setName("lblIDNumber"); // NOI18N

        txtIDNumber.setToolTipText(resourceMap.getString("txtIDNumber.toolTipText")); // NOI18N
        txtIDNumber.setName("txtIDNumber"); // NOI18N

        cmdSave.setAction(actionMap.get("save")); // NOI18N
        cmdSave.setName("cmdSave"); // NOI18N

        cmdCancel4.setAction(actionMap.get("cancel")); // NOI18N
        cmdCancel4.setName("cmdCancel4"); // NOI18N

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identificationPanelLayout.createSequentialGroup()
                        .addComponent(cmdSave)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel4)
                        .addContainerGap())
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdBrowse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(identificationPanelLayout.createSequentialGroup()
                                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDNumber)
                                    .addComponent(lblIdType)
                                    .addComponent(lblPicture))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(identificationPanelLayout.createSequentialGroup()
                                        .addComponent(txtPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addComponent(cmbIDType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 277, Short.MAX_VALUE)
                                    .addComponent(txtIDNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))))
                        .addGap(13, 13, 13))))
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdType)
                    .addComponent(cmbIDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDNumber)
                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(txtPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdBrowse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel4)
                    .addComponent(cmdSave))
                .addContainerGap())
        );

        customerTabbedPane.addTab(resourceMap.getString("identificationPanel.TabConstraints.tabTitle"), resourceMap.getIcon("identificationPanel.TabConstraints.tabIcon"), identificationPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void cancel()
    {
        int response = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to cancel?", "iLoan", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    @Action
    public void next()
    {
        customerTabbedPane.setSelectedIndex(customerTabbedPane.getSelectedIndex() + 1);
    }

    @Action
    public Task save()
    {
        return new SaveTask(org.jdesktop.application.Application.getInstance(iloan.ILoanApp.class));
    }

    private class SaveTask extends org.jdesktop.application.Task<Object, Void>
    {

        String customerID;
        String idType;
        String idNumber;
        String salutation;
        String firstName;
        String lastName;
        String otherName;
        String homeAddress;
        String homeTelephone;
        String homeMobile;
        String homeEmail;
        String workplace;
        String workAddress;
        String workTelephone;
        String workMobile;
        String workEmail;
        String dob;
        String gender;
        String registrationDate;
        String picture;

        SaveTask(org.jdesktop.application.Application app)
        {
            super(app);
            idType = cmbIDType.getSelectedItem().toString();
            idNumber = txtIDNumber.getText().trim();
            salutation = cmbSalutation.getSelectedItem().toString();
            firstName = txtFirstName.getText().trim();
            lastName = txtLastName.getText().trim();
            otherName = txtOtherNames.getText().trim();
            homeAddress = txtHomeAddress.getText().trim();
            homeTelephone = txtHomeAddress.getText().trim();
            homeMobile = txtHomeMobile.getText().trim();
            homeEmail = txtEmail.getText().trim();
            workplace = txtWorkPlace.getText().trim();
            workAddress = txtWorkAddress.getText().trim();
            workTelephone = txtWorkPhone.getText().trim();
            workMobile = txtWorkMobile.getText().trim();
            workEmail = txtWorkEmail.getText().trim();
            dob = Utilities.YMD_Formatter.format(calDOB.getDate());
            gender = cmbSex.getSelectedItem().toString();
            registrationDate = Utilities.YMD_Formatter.format(new java.util.Date());
            picture = selectedFile.getAbsolutePath();
        }

        @Override
        protected Object doInBackground()
        {
            return Customer.addCustomer(customerID, idType, idNumber, salutation, firstName, lastName, otherName, homeAddress, homeTelephone, homeMobile, homeEmail, workplace, workAddress, workTelephone, workMobile, workEmail, dob, gender, registrationDate, picture);  // return your result
        }

        @Override
        protected void succeeded(Object result)
        {
            if (result == Boolean.TRUE)
            {
                String message = "The customer was successfully added to the database.\n"
                        + "Would you like to add another?";
                int response = Utilities.showConfirmDialog(rootPane, message);
                if (response == JOptionPane.YES_OPTION)
                {
                    clearForm();
                }
                else
                {
                    dispose();
                }
            }
            else
            {
                String message = "An error occurred while adding the customer to the database.";
                Utilities.showErrorMessage(rootPane, message);
            }
        }
    }

    @Action
    public void clearForm()
    {
        this.remove(customerTabbedPane);
        initComponents();
        selectedFile = null;
    }

    @Action
    public void browse()
    {
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showOpenDialog(rootPane);
        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                selectedFile = fc.getSelectedFile();
                txtPicture.setText(selectedFile.getCanonicalPath());
            }
            catch (IOException ex)
            {
                Logger.getLogger(FrmNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calDOB;
    private javax.swing.JComboBox cmbIDType;
    private javax.swing.JComboBox cmbOccupation;
    private javax.swing.JComboBox cmbSalutation;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JButton cmdCancel1;
    private javax.swing.JButton cmdCancel2;
    private javax.swing.JButton cmdCancel3;
    private javax.swing.JButton cmdCancel4;
    private javax.swing.JButton cmdNext1;
    private javax.swing.JButton cmdNext2;
    private javax.swing.JButton cmdNext3;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton cmdSave;
    private javax.swing.JTabbedPane customerTabbedPane;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomePhone;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblIdType;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblOtherName;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWorkEmail;
    private javax.swing.JLabel lblWorkMobile;
    private javax.swing.JLabel lblWorkPhone;
    private javax.swing.JLabel lblWorkplcae;
    private javax.swing.JLabel lblworkAddress;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextArea txtHomeAddress;
    private javax.swing.JTextField txtHomeMobile;
    private javax.swing.JTextField txtHomePhone;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtOtherNames;
    private javax.swing.JTextField txtPicture;
    private javax.swing.JTextArea txtWorkAddress;
    private javax.swing.JTextField txtWorkEmail;
    private javax.swing.JTextField txtWorkMobile;
    private javax.swing.JTextField txtWorkPhone;
    private javax.swing.JTextField txtWorkPlace;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
