package iloan;

import iloan.customer.FrmAddCustomer;
import iloan.kernel.Environment;
import iloan.kernel.StatusHandlers;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import org.jdesktop.swingx.JXStatusBar;
import org.jdesktop.swingx.plaf.basic.BasicStatusBarUI;

/**
 *
 * @author mrogers
 */
public class Main extends javax.swing.JFrame
{

    private static final Logger logger = Logger.getLogger(Main.class.getName());
    FrmAddCustomer frmAddCustomer = null;

    /**
     * Creates new form Main
     */
    public Main()
    {
        setupEnvironment();
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("images/ruby.png"));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        desktopPane = new javax.swing.JDesktopPane();
        statusBar = new org.jdesktop.swingx.JXStatusBar();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        customerMenu = new javax.swing.JMenu();
        addCustomer = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iLoan - Pawn and Loan management System");
        statusBar.setPreferredSize(new java.awt.Dimension(27, 25));
        //do not add separators automatically
        statusBar.putClientProperty(BasicStatusBarUI.AUTO_ADD_SEPARATOR, Boolean.FALSE);
        statusBar.add(StatusHandlers.taskLabel);
        //use dummy label to fill empty space
        statusBar.add(new JLabel(""), JXStatusBar.Constraint.ResizeBehavior.FILL);
        //create constraint to add space of 5 at components left and right side
        JXStatusBar.Constraint ct = new JXStatusBar.Constraint(new Insets(0, 5, 0, 5));
        //statusBar.add(new JSeparator(JSeparator.VERTICAL), ct);
        //statusBar.add(new JLabel("INS"), ct);
        statusBar.add(new JSeparator(JSeparator.VERTICAL), ct);
        //statusBar.add(new JLabel("Load"), ct);
        JProgressBar progressBar = StatusHandlers.progressBar;
        //use statusbar style if available
        progressBar.setName("StatusProgressBar");
        statusBar.add(progressBar);
        //add the statusbar to the rootPane - some themes require this for proper appearance
        getRootPane().putClientProperty("Synthetica.statusBar", statusBar);
        fileMenu.setMnemonic('f');
        fileMenu.setText("File");
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/door_out.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);
        customerMenu.setMnemonic('C');
        customerMenu.setText("Customer");
        addCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/user_add.png"))); // NOI18N
        addCustomer.setMnemonic('A');
        addCustomer.setText("Add Customer");
        addCustomer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addCustomerActionPerformed(evt);
            }
        });
        customerMenu.add(addCustomer);
        menuBar.add(customerMenu);
        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloan/resources/information.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);
        setJMenuBar(menuBar);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                      .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitMenuItemActionPerformed
    {
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addCustomerActionPerformed
    {
//GEN-HEADEREND:event_addCustomerActionPerformed
        //Verify if the form is already loaded
        boolean AlreadyLoaded = isLoaded("Add Customer");
        if (AlreadyLoaded == false)
        {
            frmAddCustomer = new FrmAddCustomer();
            desktopPane.add(frmAddCustomer);
            //Load the Form
            frmAddCustomer.setVisible(true);
            frmAddCustomer.show();
            try
            {
                frmAddCustomer.setIcon(false);
                frmAddCustomer.setSelected(true);
            }
            catch (Exception e)
            {
                logger.log(Level.SEVERE, "Error displaying the form.", e);
            }
        }
    }//GEN-LAST:event_addCustomerActionPerformed

    /**
     * This function checks if a specified form is already displayed. It accepts
     * the window title in the form of a string and checks if it is already
     * loaded onto the desktop pane. It then returns a boolean depending on the
     * result of the test.
     *
     * @param FormTitle
     * @return True if a loaded frame contains the specified string in title.
     * False if no frames contains the specified string.
     */
    protected boolean isLoaded(String FormTitle)
    {
        JInternalFrame Form[] = desktopPane.getAllFrames();
        for (int i = 0; i < Form.length; i++)
        {
            if (Form[i].getTitle().equalsIgnoreCase(FormTitle))
            {
                Form[i].show();
                try
                {
                    Form[i].setIcon(false);
                    Form[i].setSelected(true);
                }
                catch (Exception e)
                {
                    logger.log(Level.SEVERE, "Error displaying form.", e);
                }
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
        try
        {
            String[] li =
            {
                "Licensee=Maurice Rogers", "LicenseRegistrationNumber=------", "Product=Synthetica", "LicenseType=Non Commercial", "ExpireDate=--.--.----", "MaxVersion=2.999.999"
            };
            UIManager.put("Synthetica.license.info", li);
            UIManager.put("Synthetica.license.key", "2BCF99E0-3738913D-F30B5EC9-622511CC-4F19572A");
            String[] li2 =
            {
                "Licensee=JYLOO Software", "LicenseRegistrationNumber=------", "Product=SyntheticaAddons", "LicenseType=For internal tests only", "ExpireDate=--.--.----", "MaxVersion=1.999.999"
            };
            UIManager.put("SyntheticaAddons.license.info", li2);
            UIManager.put("SyntheticaAddons.license.key", "CC98A980-13381C7D-30604C91-F5BC5376-776C6006");
            javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaSimple2DLookAndFeel");
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new Main().setVisible(true);
            }
        });
    }

    /**
     * This method will create the environment necessary for the program to
     * execute.
     */
    private void setupEnvironment()
    {
        Environment.createConnection();
        Environment.setMainFrame(this);
        Environment.setDesktopPane(desktopPane);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem addCustomer;
    private javax.swing.JMenu customerMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private org.jdesktop.swingx.JXStatusBar statusBar;
    // End of variables declaration//GEN-END:variables
}
